package main

// Build + run orchestrator. Run from the project root (see ../run.sh):
//   odin run tools/build.odin -file            build shaders + game, run (Vulkan validation ON)
//   odin run tools/build.odin -file -- watch   live-reload dev loop (release build: no validation)
//   odin run tools/build.odin -file -- shot    headless: drive the game, screenshot, exit
//   odin run tools/build.odin -file -- test    build with the test harness (-define:DEBUG_TEST) + run debug_test_run
// Shaders compile with validation on (glslc -Werror + spirv-val); the game reads shaders/spv/*.spv.

import "core:c"
import "core:c/libc"
import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:strings"
import "core:time"

// src : glslc shader stage. Compiles to shaders/spv/<src>.spv.
SHADERS := [][2]string{
	{"physics.comp", "compute"},
	{"fs_tri.vert", "vertex"},
	{"city.frag", "fragment"},
	{"body.vert", "vertex"},
	{"body.frag", "fragment"},
	{"bloom.frag", "fragment"},
	{"composite.frag", "fragment"},
}

sh :: proc(cmd: string) -> int {
	return int(libc.system(strings.clone_to_cstring(cmd, context.temp_allocator)))
}

soft: bool // watch mode: a failed step prints and keeps the loop alive instead of exiting

must :: proc(cmd: string) {
	if sh(cmd) != 0 {
		fmt.eprintln("build failed:", cmd)
		if !soft { os.exit(1) }
	}
}

// Regenerate the shared GLSL from the @glsl blocks, then compile every shader to SPIR-V.
prep :: proc() {
	gen_types()                // @glsl blocks → tools/gen/types.gen.odin
	must("odin run tools/gen") // reflect them → shaders/gen.glsl + accessors
	build_shaders(soft)        // GLSL → shaders/spv/*.spv (naga cross-check in watch mode)
}

// Compile every shader to shaders/spv/*.spv with validation on (glslc -Werror + spirv-val).
// naga=true additionally cross-checks each SPIR-V with naga — advisory (it can't parse all the
// legal SPIR-V glslc emits for the bindless design), so its output is shown, never gated.
build_shaders :: proc(naga: bool) {
	os.make_directory("shaders/spv")
	for s in SHADERS {
		src, stage := s[0], s[1]
		must(fmt.tprintf("glslc -I shaders --target-env=vulkan1.3 -Werror -fshader-stage=%s shaders/%s -o shaders/spv/%s.spv", stage, src, src))
		must(fmt.tprintf("spirv-val shaders/spv/%s.spv", src))
		if naga { sh(fmt.tprintf("naga shaders/spv/%s.spv", src)) } // advisory cross-check
	}
	fmt.println("shaders → shaders/spv/")
}

// Scan every .odin in the project root for `// @glsl … // @glsl-end` blocks (structs + constants,
// in any file) and the BUF_SPECS table, and write tools/gen/types.gen.odin: the blocks copied
// verbatim (so tools/gen reflects the real Odin types AND the compiler evaluates the constants),
// plus a typeid enumeration, the buffer table, and one emit_const call per constant. The only
// parsing is reading declaration names — layout + values are left to reflection / the compiler.
gen_types :: proc() {
	files, _ := filepath.glob("*.odin", context.temp_allocator)

	blob:   strings.Builder // @glsl declarations, copied verbatim
	types:  [dynamic]string // struct type names
	consts: [dynamic]string // constant names
	bufsrc: string          // the file text that holds BUF_SPECS

	for path in files {
		src, err := os.read_entire_file(path, context.temp_allocator)
		if err != nil { continue }
		text := string(src)
		if strings.contains(text, "BUF_SPECS :=") { bufsrc = text }
		B :: "// @glsl\n"
		rest := text
		for {
			i := strings.index(rest, B)
			if i < 0 { break }
			rest = rest[i + len(B):]
			j := strings.index(rest, "// @glsl-end")
			if j < 0 { fmt.eprintln("build: unterminated @glsl block in", path); os.exit(1) }
			block := rest[:j]
			rest = rest[j:]
			strings.write_string(&blob, block)
			b2 := block
			for line in strings.split_lines_iterator(&b2) {
				t := strings.trim_space(line)
				if len(t) == 0 || strings.has_prefix(t, "//") { continue }
				k := strings.index(line, "::")
				if k < 0 { continue }
				name := strings.trim_space(line[:k])
				if strings.contains(line, "struct") { append(&types, name) } else { append(&consts, name) }
			}
		}
	}
	if len(types) == 0 { fmt.eprintln("build: no `Name :: struct` in any @glsl block"); os.exit(1) }
	if bufsrc == "" { fmt.eprintln("build: BUF_SPECS not found"); os.exit(1) }

	out: strings.Builder
	strings.write_string(&out, "package main\n\nimport \"core:strings\"\n\n// AUTO-GENERATED by tools/build.odin — do not edit.\n\n")
	strings.write_string(&out, strings.to_string(blob))
	strings.write_string(&out, "\nGLSL_TYPES := []typeid{ ")
	for name, i in types { if i > 0 { strings.write_string(&out, ", ") }; strings.write_string(&out, name) }
	strings.write_string(&out, " }\n")

	// Buffers: parse each BUF_SPECS row for its GLSL accessor name (first string literal) and
	// element type (next token). Row order = bindless slot; size/host stay CPU-side.
	rows := bufsrc[strings.index(bufsrc, "BUF_SPECS"):]
	rows = rows[strings.index(rows, "{") + 1:] // into the [Res]BufSpec{ … } literal
	strings.write_string(&out, "GLSL_BUFFERS := []GBuf{ ")
	nb := 0
	for line in strings.split_lines_iterator(&rows) {
		if strings.has_prefix(strings.trim_space(line), "}") { break } // end of the literal
		q := strings.index(line, "\"");                if q < 0 { continue }
		q2 := strings.index(line[q + 1:], "\"");        if q2 < 0 { continue }
		glsl := line[q + 1 : q + 1 + q2]
		after := strings.trim_left(line[q + 1 + q2 + 1:], " ,")
		ce := strings.index(after, ",");                if ce < 0 { continue }
		if nb > 0 { strings.write_string(&out, ", ") }
		fmt.sbprintf(&out, "{{\"%s\", %s}}", glsl, strings.trim_space(after[:ce]))
		nb += 1
	}
	strings.write_string(&out, " }\n")
	if nb == 0 { fmt.eprintln("build: no rows parsed from BUF_SPECS"); os.exit(1) }

	// One emit_const call per constant — tools/gen resolves value + GLSL type by reflection.
	strings.write_string(&out, "emit_consts :: proc(b: ^strings.Builder) {\n")
	for name in consts { fmt.sbprintf(&out, "\temit_const(b, \"%s\", %s)\n", name, name) }
	strings.write_string(&out, "}\n")

	os.make_directory("tools/gen")
	_ = os.write_entire_file("tools/gen/types.gen.odin", transmute([]u8)strings.to_string(out))
}

main :: proc() {
	mode := len(os.args) > 1 ? os.args[1] : "run"

	// watch: the HUMAN's live-reload play loop (runtime validation OFF). Own loop below; no
	// GPU-AV pass — it loads fast and must survive a failing compile. Claude must NOT use watch.
	if mode == "watch" {
		watch()
		return
	}

	// `shot` is a headless capture meant to run ALONGSIDE a live `watch` session, so it must not
	// disturb it: don't pkill the running game, and build to a separate binary (toomanymachines-shot)
	// so the two never fight over the executable file (building over a running binary → ETXTBSY,
	// which is why every launch-a-game path pkills first). Every other mode replaces the game.
	shot := mode == "shot"
	bin := shot ? "toomanymachines-shot" : "toomanymachines"
	if !shot { sh("pkill -x toomanymachines 2>/dev/null; sleep 0.1") }
	prep()

	// `test` compiles the debug_test_run harness in (debug.odin); every other mode leaves
	// dbg_test_fn nil, so gpuav/shot/normal runs of this same binary are unaffected.
	build := fmt.tprintf("odin build . -out:%s -debug", bin)
	if mode == "test" { build = strings.concatenate({build, " -define:DEBUG_TEST=true"}, context.temp_allocator) }
	must(build)

	// GPU-Assisted validation pass: run the sim headless under GPU-AV (runtime descriptor/OOB
	// checks the CPU-side layers can't see). Aborts non-zero on any finding.
	fmt.println(">> GPU-Assisted validation pass…")
	must(fmt.tprintf("./%s gpuav", bin))

	arg := mode == "shot" ? " shot" : ""
	fmt.printf("EXIT: %d\n", sh(fmt.tprintf("./%s%s", bin, arg)) >> 8 & 0xff)
}

// --- watch: live-reload dev loop -------------------------------------------
// Two inotify watches: the root (.odin saves → regen + recompile shaders + rebuild + relaunch)
// and shaders/ (.glsl saves → recompile SPIR-V only; the running game reloads the new .spv on its
// own). Everything runs in-process (prep/build_shaders/odin build) — a failed step prints and the
// loop lives on (soft=true). Flat project, no recursive scan.
foreign import c_ "system:c"
foreign c_ {
	inotify_init      :: proc() -> c.int ---
	inotify_add_watch :: proc(fd: c.int, path: cstring, mask: c.uint) -> c.int ---
	read              :: proc(fd: c.int, buf: rawptr, count: c.size_t) -> c.ssize_t ---
	poll              :: proc(fds: rawptr, nfds: c.ulong, timeout: c.int) -> c.int ---
}
Poll_Fd :: struct { fd: c.int, events, revents: c.short }
Inotify_Event :: struct #packed { wd: c.int, mask, cookie, len: c.uint }
WATCH_MASK :: 0x00000002 | 0x00000080 | 0x00000008 // IN_MODIFY | IN_MOVED_TO | IN_CLOSE_WRITE

// Rebuild + relaunch as a RELEASE build (no -debug → ODIN_DEBUG off → validation compiled out):
// this is the human's frame-time loop, fast and unvalidated. `./run.sh`/shot/test build -debug.
launch :: proc() {
	fmt.println("Building…")
	sh("pkill -x toomanymachines 2>/dev/null; sleep 0.1")
	if sh("odin build . -out:toomanymachines") == 0 {
		fmt.println("OK — launching (release build: no validation, fast)")
		sh("nohup ./toomanymachines >/dev/null 2>&1 &")
	} else {
		fmt.println("BUILD FAILED")
	}
}

watch :: proc() {
	fmt.println(">> watch = the HUMAN's play loop (release build, no validation). Claude: use ./run.sh / shot / test.")
	soft = true
	prep(); launch() // initial build + launch

	fd := inotify_init()
	if fd < 0 { fmt.eprintln("inotify_init failed"); return }
	if inotify_add_watch(fd, ".", WATCH_MASK) < 0 { fmt.eprintln("add_watch . failed"); return }
	if inotify_add_watch(fd, "shaders", WATCH_MASK) < 0 { fmt.eprintln("add_watch shaders failed"); return }
	fmt.println("Watching . (.odin) + shaders (.glsl)")

	buf: [4096]u8
	fds := Poll_Fd{fd = fd, events = 0x0001 /*POLLIN*/}
	for {
		if poll(&fds, 1, -1) <= 0 || (fds.revents & 0x0001) == 0 { continue }
		time.sleep(120 * time.Millisecond) // debounce editors writing several files at once

		odin, glsl := false, false
		for {
			n := read(fd, &buf[0], 4096)
			if n <= 0 { break }
			for i := 0; i < int(n); {
				ev := (^Inotify_Event)(&buf[i])
				if ev.len > 0 {
					name := string(cstring(&buf[i + size_of(Inotify_Event)]))
					if strings.has_suffix(name, ".odin") {
						odin = true // any .odin may hold an @glsl block
					} else if name != "gen.glsl" && has_shader_ext(name) {
						glsl = true // gen.glsl is generated, not a source
					}
				}
				i += size_of(Inotify_Event) + int(ev.len)
			}
			if int(n) < 4096 { break }
		}
		if odin      { prep(); launch() }   // .odin → regen GLSL, recompile shaders, rebuild + relaunch
		else if glsl { build_shaders(true) } // .glsl → recompile .spv; the running game reloads it
	}
}

has_shader_ext :: proc(name: string) -> bool {
	for ext in ([]string{".vert", ".frag", ".comp", ".glsl"}) { if strings.has_suffix(name, ext) { return true } }
	return false
}
